###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing import Dict, Generic, List, Optional, TypeVar, Union, Literal

from . import types
from .types import Checked, Check

###############################################################################
#
#  These types are used for streaming, for when an instance of a type
#  is still being built up and any of its fields is not yet fully available.
#
###############################################################################

T = TypeVar('T')
class StreamState(BaseModel, Generic[T]):
    value: T
    state: Literal["Pending", "Incomplete", "Complete"]


class Appointment(BaseModel):
    day_of_week: Optional[str] = None
    month: Optional[str] = None
    date: Optional[int] = None
    year: Optional[int] = None
    hour: Optional[int] = None
    minute: Optional[int] = None
    ampm: Optional[str] = None

class DropOffPackageReceipt(BaseModel):
    line_item: List["ReceiptItem"]
    location: Optional[str] = None
    address: Optional[str] = None
    day_of_week: Optional[str] = None
    day: Optional[int] = None
    month: Optional[str] = None
    year: Optional[int] = None
    hour: Optional[int] = None
    minute: Optional[int] = None
    ampm: Optional[str] = None
    total_packages: Optional[int] = None
    total_packages_ui: Optional[str] = None

class NutritionLabel(BaseModel):
    product: Optional[str] = None
    description: Optional[str] = None
    calories: Optional[int] = None
    fat: Optional[int] = None
    fat_ui: Optional[str] = None
    fat_dv: Optional[float] = None
    sodium: Optional[int] = None
    sodium_ui: Optional[str] = None
    sodium_dv: Optional[float] = None
    carb: Optional[int] = None
    carb_ui: Optional[str] = None
    carb_dv: Optional[float] = None
    protein: Optional[int] = None
    protein_ui: Optional[str] = None
    protein_dv: Optional[float] = None

class ReceiptItem(BaseModel):
    tracking_number: Optional[str] = None
    weight: Optional[float] = None
    weight_ui: Optional[str] = None
